# Generated by Django 6.0.3 on 2026-07-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('subject', 'date', 'start_time')},
        ),
    ]
