# Generated by Django 6.0.3 on 2026-04-03 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '__first__'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-marked_at'],
                'unique_together': {('student', 'class_session')},
            },
        ),
        migrations.CreateModel(
            name='FaceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enrolled', models.BooleanField(default=False)),
                ('total_photos_registered', models.IntegerField(default=0, help_text='Number of photos used for enrollment (target: 5)')),
                ('registration_confidence', models.FloatField(default=0.0, help_text='Average quality score across all enrolled photos (0-1)')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='accounts.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_confidence', models.FloatField(help_text='KNN confidence score (0.0 to 1.0)')),
                ('distance_to_nearest', models.FloatField(help_text='Euclidean distance to nearest stored embedding')),
                ('best_matching_photo_number', models.IntegerField(blank=True, help_text='Photo number of the best matching embedding used for attendance marking', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Client-captured GPS latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Client-captured GPS longitude', null=True)),
                ('distance_from_classroom', models.FloatField(blank=True, help_text='Distance in meters from classroom location', null=True)),
                ('liveness_passed', models.CharField(choices=[('PASS', 'Liveness Check Passed'), ('FAIL', 'Liveness Check Failed'), ('UNKNOWN', 'Liveness Check Not Performed')], default='UNKNOWN', help_text='Result of liveness detection', max_length=10)),
                ('face_image_path', models.TextField(blank=True, help_text='Path to the captured face image used for matching', null=True)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Set to True if admin reviewing finds suspicious activity')),
                ('timestamp_signed', models.TextField(blank=True, help_text='Digitally signed timestamp from client for audit trail', null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_log', to='attendance.attendance')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['attendance'], name='attendance__attenda_561a89_idx'), models.Index(fields=['created_at'], name='attendance__created_c5bef6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.JSONField()),
                ('photo_number', models.IntegerField()),
                ('quality_score', models.FloatField(default=0.0, help_text='Face detection confidence (0-1). Higher is better.')),
                ('face_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='attendance.facedata')),
            ],
            options={
                'ordering': ['photo_number'],
                'unique_together': {('face_data', 'photo_number')},
            },
        ),
    ]
