# Generated by Django 6.0.3 on 2026-05-03 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='detection_confidence',
            field=models.FloatField(default=0.0, help_text='Face recognition confidence score (0-1) from ML service'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='frame_detected',
            field=models.DateTimeField(blank=True, help_text='Timestamp when face was detected in video frame', null=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('marked_students', models.JSONField(default=list, help_text='List of student user IDs detected during session')),
                ('class_session', models.ForeignKey(help_text='Class session this attendance is for', on_delete=django.db.models.deletion.CASCADE, related_name='real_time_sessions', to='academics.classsession')),
                ('initiated_by', models.ForeignKey(help_text='Teacher who initiated this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_session',
            field=models.ForeignKey(blank=True, help_text='Link to the real-time session during which this attendance was marked', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.attendancesession'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('attendance_session__isnull', False)), fields=('student', 'attendance_session'), name='unique_attendance_per_session'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('attendance_session__isnull', True)), fields=('student', 'class_session'), name='unique_attendance_manual_marking'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['class_session', 'started_at'], name='attendance__class_s_101254_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['ended_at'], name='attendance__ended_a_39f3ed_idx'),
        ),
    ]
