# Generated by Django 6.0.3 on 2026-07-02 11:25

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('attendance', '0005_fix_attendance_flow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='classsessiontemplate',
            name='unique_template_per_subject_time',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__templat_337a48_idx',
            old_name='attendance_a_template_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__session_f739c3_idx',
            old_name='attendance_a_date_time_idx',
        ),
        migrations.RenameIndex(
            model_name='classsessiontemplate',
            new_name='attendance__subject_e77fca_idx',
            old_name='attendance_c_subject_day_idx',
        ),
        migrations.RenameIndex(
            model_name='classsessiontemplate',
            new_name='attendance__is_acti_6050d0_idx',
            old_name='attendance_c_is_active_idx',
        ),
        # REPLACE IT WITH THIS:
        migrations.RemoveField(
            model_name='classsessiontemplate',
            name='id',
        ),
        migrations.AddField(
            model_name='classsessiontemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='classsessiontemplate',
            unique_together={('subject', 'day_of_week', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'attendance_session'), name='unique_attendance_per_session'),
        ),
    ]
