# Generated by Django 6.0.3 on 2026-07-02 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('attendance', '0006_recreate_classsessiontemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_per_session',
        ),
        migrations.RemoveConstraint(
            model_name='classsessiontemplate',
            name='unique_template_per_subject_time',
        ),
        # --- ALL RENAME INDEX BLOCKS REMOVED FROM HERE ---
        migrations.AlterUniqueTogether(
            name='classsessiontemplate',
            unique_together={('subject', 'day_of_week', 'start_time')},
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'attendance_session'), name='unique_attendance_per_session'),
        ),
    ]