# Generated by Django 6.0.3 on 2026-07-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_unique_attendance_per_session_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__templat_337a48_idx',
            old_name='attendance_a_template_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__templat_337a48_idx',
            old_name='attendance_a_template_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__session_f739c3_idx',
            old_name='attendance_a_date_time_idx',
        ),
        migrations.RenameIndex(
            model_name='classsessiontemplate',
            new_name='attendance__subject_e77fca_idx',
            old_name='attendance_c_subject_day_idx',
        ),
        migrations.RenameIndex(
            model_name='classsessiontemplate',
            new_name='attendance__is_acti_6050d0_idx',
            old_name='attendance_c_is_active_idx',
        ),
    ]
